### ISSUE TITLE
dns server causes overflowMsg

### ISSUE THREAD

**Issue by sanyo0714** [miekg/dns#1128]
code ### @v1.1.27 server.go
```
461 for srv.isStarted() {
462		m, s, err := reader.ReadUDP(l, rtimeout)
463		if err != nil {
464			if !srv.isStarted() {
465				return nil
466			}
467			if netErr, ok := err.(net.Error); ok && netErr.Temporary() {
468				continue
469			}
470			return err
471		}
472		if len(m) < headerSize {
473			if cap(m) == srv.UDPSize {
474				srv.udpPool.Put(m[:srv.UDPSize])
475			}
476			continue
477		}
478		wg.Add(1)
479		go srv.serveUDPPacket(&wg, m, l, s)  //  Srv. serveUDPPacket will eventually call socket writeLock()
480 }
```

@go/src/internal/poll/fd_mutex.go
```
// lock adds a reference to mu and locks mu.
// It reports whether mu is available for reading or writing.
func (mu *fdMutex) rwlock(read bool) bool {
	var mutexBit, mutexWait, mutexMask uint64
	var mutexSema *uint32
	if read {
		mutexBit = mutexRLock
		mutexWait = mutexRWait
		mutexMask = mutexRMask
		mutexSema = &mu.rsema
	} else {
		mutexBit = mutexWLock
		mutexWait = mutexWWait
		mutexMask = mutexWMask
		mutexSema = &mu.wsema
	}
	for {
		old := atomic.LoadUint64(&mu.state)
		if old&mutexClosed != 0 {
			return false
		}
		var new uint64
		if old&mutexBit == 0 {
			// Lock is free, acquire it.
			new = (old | mutexBit) + mutexRef
			if new&mutexRefMask == 0 {
				panic(overflowMsg)
			}
		} else {
			// Wait for lock.
			new = old + mutexWait
			if new&mutexMask == 0 {
				panic(overflowMsg)
			}
		}
		if atomic.CompareAndSwapUint64(&mu.state, old, new) {
			if old&mutexBit == 0 {
				return true
			}
			runtime_Semacquire(mutexSema)
			// The signaller has subtracted mutexWait.
		}
	}
}
```

The function (Srv. serveUDPPacket) will eventually call socket writeLock().When the number of the requests is very large, the number of goroutines will increase indefinitely. This phenomenon will lead to an error with overflow message("too many concurrent operations on a single file or socket (max 1048575)").

```
[ERROR] Recovered from panic in server: "dns://:53"
panic: too many concurrent operations on a single file or socket (max 1048575) [recovered]
goroutine 15814150 [running]:
internal/poll.(*fdMutex).rwlock(0xc00025c380, 0xd3a0942b00, 0x53e672)
	/usr/local/go/src/internal/poll/fd_mutex.go:147 +0x13f
internal/poll.(*FD).writeLock(...)
	/usr/local/go/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).WriteMsg(0xc00025c380, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a19af580, 0x20, 0x20, 0x1ed8600, 0xd3a19af5a0, 0x0, ...)
	/usr/local/go/src/internal/poll/fd_unix.go:345 +0x7a
net.(*netFD).writeMsg(0xc00025c380, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a19af580, 0x20, 0x20, 0x1ed8600, 0xd3a19af5a0, 0xd3a0942cd8, ...)
	/usr/local/go/src/net/fd_unix.go:232 +0xaa
net.(*UDPConn).writeMsg(0xc0001180f8, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a19af580, 0x20, 0x20, 0xd3a15f50b0, 0x6cc2cb, 0xd3a2053880, ...)
	/usr/local/go/src/net/udpsock_posix.go:94 +0x114
net.(*UDPConn).WriteMsgUDP(0xc0001180f8, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a19af580, 0x20, 0x20, 0xd3a15f50b0, 0xe, 0xd300010001, ...)
	/usr/local/go/src/net/udpsock.go:186 +0xa5
github.com/miekg/dns.WriteToSessionUDP(0xc0001180f8, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a15ed1a0, 0xd3a19bed80, 0x2a, 0x2b)
	/root/go/pkg/mod/github.com/miekg/dns@v1.1.27/udp.go:52 +0xa8
github.com/miekg/dns.(*response).Write(0xd3a20d5e60, 0xd3a19bed80, 0x2a, 0x2b, 0xd3a19bed80, 0x2a, 0x2b)
	/root/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:687 +0x265
github.com/miekg/dns.(*response).WriteMsg(0xd3a20d5e60, 0xd3a20f87e0, 0xd3a20f87e0, 0x0)
	/root/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:675 +0xbb
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0xd3a20e6fa0, 0xd3a20f87e0, 0xd3a20f86c0, 0x1f2da80)
	/home/coredns-test/coredns-1.6.7/request/writer.go:20 +0xc8

```

**Comment by chantra** [comment]
I think this is similar to #997
