### ISSUE TITLE
crash while parsing malformed DNS packet

### ISSUE THREAD

**Issue by alonek1** [miekg/dns#1375]
Hi,
Recently we were fuzzing a DNS service that was using this library.
The error that happen while processing a malformed packet is as follow:

```
panic: runtime error: invalid memory address or nil pointer dereference                                                            
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1270337]                                                            
goroutine 162 [running]:                                                                                                          
github.com/miekg/dns.(*Msg).SetReply(...)                                                                                          
        /builder/vendor/github.com/miekg/dns/defaults.go:16                                                                        
github.com/miekg/dns.(*Msg).SetRcode(...)                                                                                          
        /builder/vendor/github.com/miekg/dns/defaults.go:56                                                                        
git.redacted.cominfrastructure/delivery/dns/server/dns.(*Request).ReplyError(0xc000164ca0, 0x2)                                  
        /builder/server/dns/request.go:96 +0x37                                                                                    
git.redacted.com/infrastructure/delivery/dns/server/dns.(*Server).ServeDNS(0xc0004d2940, {0x1851b68, 0xc000136400}, 0x78?)        
        /builder/server/dns/server.go:66 +0x405                                                                                    
github.com/miekg/dns.(*Server).serveDNS(0xc0002f6b40, {0xc0004fc400, 0xc, 0x200}, 0xc000136400)                                    
        /builder/vendor/github.com/miekg/dns/server.go:651 +0x4db                                                                  
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0002f6b40, 0x0?, {0xc0004fc400, 0xc, 0x200}, {0x184fd20?, 0xc00034e010}, 0xc0003a6
540, {0x0, 0x0})                                                                                                                  
        /builder/vendor/github.com/miekg/dns/server.go:591 +0x185                                                                  
created by github.com/miekg/dns.(*Server).serveUDP
        /builder/vendor/github.com/miekg/dns/server.go:521 +0x485
```​

the malformed packet is also here:

https://anonymshare.com/LzLn/badpacket.pcap

**Comment by miekg** [comment]
Extracting the bytes from that pcap, request: `810f01000001000000000000` and what wireshark claims is also malformed (but also overlaps with IP header), so unsure, but `000028675140004011f8f15c72113c5c721062` are happily unpacked without trouble

**Comment by yaa110** [comment]
The `dns *Msg` or `request *Msg` is provided by `ServeDNS`. I think it should be documented that the msg argument of `ServeDNS` could be `nil`.

**Comment by tmthrgd** [comment]
> The `dns *Msg` or `request *Msg` is provided by `ServeDNS`. I think it should be documented that the provided `r *Msg` argument of `ServeDNS` could be `nil`.

The `r *Msg` argument of `ServeDNS` will **never** be `nil`, regardless of the received message.
