### ISSUE TITLE
frequently panic in Msg.Pack method

### ISSUE THREAD

**Issue by missdeer** [miekg/dns#354]
I'm using the latest code from the repository, the code snippet:

```golang
func exchange(server string, c *dns.Client, r *dns.Msg, resp chan *dns.Msg) {
	if rs, _, err := c.Exchange(r, server); err == nil {
		resp <- rs
	} else {
		resp <- nil
		common.Errorf("query dns %s from %s failed, %+v\n", r.Question[0].Name, server, err)
	}
}
...
		if m, err := rs.Pack(); err == nil {
			w.Write(m)
		}
```
But Pack() method crashes frequently.
```
goroutine 22 [running]:
panic(0xa36ec0, 0xc082002090)
        X:/go/src/runtime/panic.go:464 +0x3f4
github.com/miekg/dns.(*Msg).Len(0xc0822d02d0, 0xc082a975a0)
        X:/Shareware/yiili/src/github.com/miekg/dns/msg.go:1738 +0x24a
github.com/miekg/dns.(*Msg).PackBuffer(0xc0822d02d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        X:/Shareware/yiili/src/github.com/miekg/dns/msg.go:1575 +0x3cb
github.com/miekg/dns.(*Msg).Pack(0xc0822d02d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        X:/Shareware/yiili/src/github.com/miekg/dns/msg.go:1507 +0x5a
```

**Comment by miekg** [comment]
Can you print the packet before you pack? The above stack trace doesn't exactly point out something obvious...

**Comment by andrewtj** [comment]
I think you might have a `nil` in `m.Answer`. How is the `m` in question constructed and manipulated?

**Comment by missdeer** [comment]
@andrewtj I think so. But I thought `rs` is returned by `dns.Client.Exchange` method, it should be packed without panic.

**Comment by andrewtj** [comment]
It should. Can you do as @miekg suggested and print `rs`? `log.Printf("struct:\n%V\nmsg:\n%s", rs, rs)` immediately after `Exchange` and immediately before `Pack` might show the anomaly.

**Comment by missdeer** [comment]
I have some code to filter out nil answers:

```golang
		for i := len(rs.Answer) - 1; i >= 0; i-- {
			if rs.Answer[i] == nil {
				common.Warningf("found nil answer in %s's result: %V, %s", r.Question[0].Name, rs, rs)
				rs.Answer = append(rs.Answer[:i], rs.Answer[i+1:]...)
			}
		}
```

And got some logs:

```
18:54:34.450 W ▶ found nil answer in local.'s result: &{{%!V(uint16=39035) %!V(bool=true) %!V(int=0) %!V(bool=false) %!V(bool=false) %!V(bool=true) %!V(bool=true) %!V(bool=false) %!V(bool=false) %!V(bool=false) %!V(int=0)} %!V(bool=false) [{%!V(string=local.) %!V(uint16=6) %!V(uint16=1)}] [<nil>] [] []}, ;; opcode: QUERY, status: NOERROR, id: 39035
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;local. IN       SOA

;; ANSWER SECTION:
18:54:34.456 W ▶ found nil answer in local.'s result: &{{%!V(uint16=34953) %!V(bool=true) %!V(int=0) %!V(bool=false) %!V(bool=false) %!V(bool=true) %!V(bool=true) %!V(bool=false) %!V(bool=false) %!V(bool=false) %!V(int=0)} %!V(bool=false) [{%!V(string=local.) %!V(uint16=6) %!V(uint16=1)}] [<nil>] [] []}, ;; opcode: QUERY, status: NOERROR, id: 34953
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;local. IN       SOA

;; ANSWER SECTION:
```

**Comment by miekg** [comment]
If it's so localised, are you able to capture an incoming packet that you
believe triggers this. Something is adding an empty answer and I find it
hard to believe it is Exchange.

**Comment by andrewtj** [comment]
@missdeer are those log entries immediately after calling `Exchange`? If so can you instrument `Conn.ReadMsg()` to dump the messages byte slice so we can take a look at it?

**Comment by andrewtj** [comment]
@missdeer got an update for us?

**Comment by missdeer** [comment]
it's not easy for me to capture the raw data when the issue happens, so i check the nil answer in my application
