### ISSUE TITLE
no reflection fallout

### ISSUE THREAD

**Issue by miekg** [miekg/dns#379]
Seeing this in CoreDNS tests:

~~~
PASS
ok  	github.com/miekg/coredns/middleware/errors	1.015s
2016/06/14 12:05:57 [WARNING] Forwarding cycle detected, refusing msg: example.org.
--- FAIL: TestStubLookup (0.01s)
panic: interface conversion: dns.RR is *dns.RR_Header, not *dns.OPT [recovered]
	panic: interface conversion: dns.RR is *dns.RR_Header, not *dns.OPT
goroutine 512 [running]:
testing.tRunner.func1(0xc8203d46c0)
	/tmp/workdir/go/src/testing/testing.go:450 +0x1f5
github.com/miekg/dns.(*Msg).IsEdns0(0xc8203d4900, 0xc8200fc340)
	/home/travis/gopath/src/github.com/miekg/dns/defaults.go:151 +0x1f8
github.com/miekg/coredns/middleware.(*State).SizeAndDo(0xc8202196c0, 0xc8203d4900, 0xc8203f09c0)
	/home/travis/gopath/src/github.com/miekg/coredns/middleware/state.go:137 +0x114
github.com/miekg/coredns/middleware/etcd.Stub.ServeDNS(0x0, 0x0, 0xc820137260, 0x3, 0x3, 0xe36210, 0x6, 0x0, 0x0, 0xc820177860, ...)
	/home/travis/gopath/src/github.com/miekg/coredns/middleware/etcd/stub_handler.go:36 +0x5d3
github.com/miekg/coredns/middleware/etcd.Etcd.ServeDNS(0x0, 0x0, 0xc820137260, 0x3, 0x3, 0xe36210, 0x6, 0x0, 0x0, 0xc820177860, ...)
	/home/travis/gopath/src/github.com/miekg/coredns/middleware/etcd/handler.go:34 +0x5f0
github.com/miekg/coredns/middleware/etcd.TestStubLookup(0xc8203d46c0)
	/home/travis/gopath/src/github.com/miekg/coredns/middleware/etcd/stub_test.go:26 +0x426
testing.tRunner(0xc8203d46c0, 0x122a4a0)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
goroutine 1 [chan receive]:
testing.RunTests(0xfa7830, 0x122a3e0, 0x9, 0x9, 0x1)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc82009fef0, 0x1)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	github.com/miekg/coredns/middleware/etcd/_test/_testmain.go:70 +0x210
~~~

**Comment by miekg** [comment]
This diff fixes this for OPT:
~~~
+       rr := new(OPT)
+       rr.Hdr = h
+
        if noRdata(h) {
-               return &h, off, 
+               return rr, off, 
        }
        var err error
        rdStart := off
        _ = rdStart
 
-       rr := new(OPT)
-       rr.Hdr = h
-
~~~
In short, don't return *just* the header, return the empty RR with the header.
