### ISSUE TITLE
panics raised in compressionLenHelper() and packDomainName()

### ISSUE THREAD

**Issue by johnmah** [miekg/dns#389]
i believe that there is a race condition that is causing panics around the code that modifies dns.Compress flag when determining the size of a compressed packet. unfortunately i do not have the original domain(s) that cause the panic at this time.

note the stack trace for PackDomainName() and packDomainName, in theory i would think that these parameters should be almost identical.

i am going to try and fix this by adding a function that determines the size of the compressed package without modifying the internal dns.Compress state.

```
panic: assignment to entry in nil map

goroutine 19713 [running]:
panic(0x86e0e0, 0xc82019b060)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/miekg/dns.compressionLenHelper(0x0, 0xc8204749a0, 0x11)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:969 +0x150
github.com/miekg/dns.(*Msg).Len(0xc820495e60, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:915 +0xa51
github.com/miekg/dns.(*Msg).PackBuffer(0xc820495e60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:737 +0x3ab
github.com/miekg/dns.(*Msg).Pack(0xc820495e60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:665 +0x53
github.com/miekg/dns.(*response).WriteMsg(0xc82011bb80, 0xc820495e60, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:671 +0x275
main.(*DNSServer).handleForward(0xc820192140, 0x7f56d6448e18, 0xc82011bb80, 0xc820147050)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/dnserver.go:533 +0x96d
main.(*DNSServer).(main.handleForward)-fm(0x7f56d6448e18, 0xc82011bb80, 0xc820147050)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/dnserver.go:64 +0x3e
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc82017ada0, 0x7f56d6448e18, 0xc82011bb80, 0xc820147050)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:84 +0x3a
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc82017ad90, 0x7f56d6448e18, 0xc82011bb80, 0xc820147050)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:210 +0xbb
github.com/miekg/dns.(*Server).serve(0xc82011f040, 0x7f56d6440598, 0xc8201435f0, 0x7f56d6444d08, 0xc82017ad90, 0xc820137400, 0x22, 0x200, 0xc820116128, 0xc820491540, ...)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:577 +0x7ef
created by github.com/miekg/dns.(*Server).serveUDP
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:531 +0x3e1
```

```
panic: assignment to entry in nil map

goroutine 106869 [running]:
panic(0x86e0e0, 0xc8205568b0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/miekg/dns.packDomainName(0xc820545420, 0x11, 0xc820316000, 0x83, 0x83, 0x46, 0x0, 0x1, 0x34, 0x0, ...)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:254 +0xabd
github.com/miekg/dns.PackDomainName(0xc820545420, 0x11, 0xc820316000, 0x83, 0x83, 0x42, 0x0, 0xffffffffffffff01, 0x34, 0x0, ...)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:152 +0x8d
github.com/miekg/dns.RR_Header.pack(0xc820545420, 0x11, 0x1900010001, 0x4, 0xc820316000, 0x83, 0x83, 0x42, 0x0, 0x1, ...)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg_helpers.go:109 +0xc7
github.com/miekg/dns.(*A).pack(0xc820212740, 0xc820316000, 0x83, 0x83, 0x42, 0x0, 0xc820316001, 0x42, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/zmsg.go:9 +0x98
github.com/miekg/dns.PackRR(0x7f9436b21660, 0xc820212740, 0xc820316000, 0x83, 0x83, 0x42, 0x0, 0x1, 0x42, 0x0, ...)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:562 +0x128
github.com/miekg/dns.(*Msg).PackBuffer(0xc820487320, 0x0, 0x0, 0x0, 0xc820316000, 0x83, 0x83, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:755 +0x632
github.com/miekg/dns.(*Msg).Pack(0xc820487320, 0x0, 0x0, 0x0, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/msg.go:665 +0x53
github.com/miekg/dns.(*response).WriteMsg(0xc82043d000, 0xc820487320, 0x0, 0x0)
        /jenkins/workspace/dnsproxy-tcpproxy-build/dnsproxy/src/github.com/miekg/dns/server.go:671 +0x275
```

**Comment by miekg** [comment]
i.e. this should show up with -race in a test.

**Comment by miekg** [comment]
Can this be closed?
