### ISSUE TITLE
UDP timeout responding to SOA request

### ISSUE THREAD

**Issue by ear7h** [miekg/dns#564]
I'm writing a DNS server and using the standard constructs of this package to serve the most common record types. I've gotten A, AAAA, NS, and CNAME records to work with the following pattern but, when querying for SOA, I get a UDP timeout both with `dns.Exchange()` and `dig`. 

``` go
func TestLibSOA(t *testing.T) {
	go dns.ListenAndServe(":4453", "udp", makeTDNSHandler())

	m := new(dns.Msg)
	m.SetQuestion("host.com.", dns.TypeSOA)

	r, err := dns.Exchange(m, "127.0.0.1:4453")
	if err != nil {
		panic(err)
	}

	fmt.Println(r)
}

func makeTDNSHandler() dns.HandlerFunc {
	_timeout := 120
	return func(w dns.ResponseWriter, r *dns.Msg) {
		msg := new(dns.Msg)

		msg.SetReply(r)

		msg.Answer = []dns.RR{
			&dns.SOA{
				Hdr: dns.RR_Header{
					Name:   "host.com.",
					Rrtype: dns.TypeSOA,
					Class:  dns.ClassINET,
					Ttl:    uint32(_timeout),
				},
				Ns:      "ns1.host.com.",
				Mbox:    "my\\.email.host.com",
				Serial:  serial(),
				Refresh: uint32(_timeout),
				Retry:   uint32(_timeout / 4),
				Expire:  uint32(_timeout * 6),
				Minttl:  uint32(_timeout / 2),
			},
		}

		w.WriteMsg(msg)
	}
}

func serial() uint32 {
	t := time.Now()

	yyyymmdd := (t.Year() * 10000) + (int(t.Month()) * 100) + (t.Day())
	return uint32(yyyymmdd * 100) 
}
```

Running the test yields this error:

```
--- FAIL: TestLibSOA (2.00s)
panic: read udp 127.0.0.1:64719->127.0.0.1:4453: i/o timeout [recovered]
	panic: read udp 127.0.0.1:64719->127.0.0.1:4453: i/o timeout

goroutine 8 [running]:
testing.tRunner.func1(0xc42013e0f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x1392240, 0xc420152050)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/ear7h/edns/master.TestLibSOA(0xc42013e0f0)
	/Users/julio/lib/go/src/github.com/ear7h/edns/master/dns_test.go:64 +0x17a
testing.tRunner(0xc42013e0f0, 0x140e108)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/ear7h/edns/master	2.015s
```

**Comment by andrewtj** [comment]
A response isn't being sent because the SOA Mbox isn't a fully qualified domain name. I found this by checking the return value of `WriteMsg`.

**Comment by ear7h** [comment]
@andrewtj thank you, didn't realize that `WriteMsg` had a return value. The problem was that the email didn't have a trailing period.
