### ISSUE TITLE
travis/build fails: test ran too long

### ISSUE THREAD

**Issue by miekg** [miekg/dns#575]
from: https://travis-ci.org/miekg/dns/jobs/303528710

obvious suspect: #570 

~~~
 go get -t -v ./...
github.com/miekg/dns/internal/socket
github.com/miekg/dns
github.com/miekg/dns/dnsutil
github.com/miekg/dns/idn
615.49s$ go test $TESTS
=== RUN   TestDialUDP
--- PASS: TestDialUDP (0.00s)
=== RUN   TestClientSync
--- PASS: TestClientSync (0.00s)
=== RUN   TestClientLocalAddress
--- PASS: TestClientLocalAddress (0.00s)
=== RUN   TestClientTLSSyncV4
--- PASS: TestClientTLSSyncV4 (0.04s)
=== RUN   TestClientSyncBadID
--- PASS: TestClientSyncBadID (0.00s)
=== RUN   TestClientEDNS0
--- PASS: TestClientEDNS0 (0.00s)
=== RUN   TestClientEDNS0Local
--- PASS: TestClientEDNS0Local (0.00s)
=== RUN   TestClientConn
--- PASS: TestClientConn (0.00s)
=== RUN   TestTruncatedMsg
--- PASS: TestTruncatedMsg (0.00s)
=== RUN   TestTimeout
--- PASS: TestTimeout (0.00s)
=== RUN   TestConcurrentExchanges
SIGQUIT: quit
PC=0x488631 m=0 sigcode=0
goroutine 0 [idle]:
runtime.futex(0xb5bf40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x45fe42, 0x0, 0x0, 0x7ffdf5151f00, ...)
	/home/travis/.gimme/versions/go/src/runtime/sys_linux_amd64.s:526 +0x21
runtime.futexsleep(0xb5bf40, 0x0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xb5bf40)
	/home/travis/.gimme/versions/go/src/runtime/lock_futex.go:151 +0xc7
runtime.stopm()
	/home/travis/.gimme/versions/go/src/runtime/proc.go:1951 +0xe5
runtime.findrunnable(0xc420032500, 0x0)
	/home/travis/.gimme/versions/go/src/runtime/proc.go:2407 +0x2bc
runtime.schedule()
	/home/travis/.gimme/versions/go/src/runtime/proc.go:2533 +0x151
runtime.goexit0(0xc42012ca80)
	/home/travis/.gimme/versions/go/src/runtime/proc.go:2705 +0x212
runtime.mcall(0x0)
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:351 +0x5b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc420108000, 0x92c99f, 0x17, 0x942160, 0xc420065c01)
	/home/travis/.gimme/versions/go/src/testing/testing.go:813 +0x568
testing.runTests.func1(0xc420108000)
	/home/travis/.gimme/versions/go/src/testing/testing.go:1036 +0xa5
testing.tRunner(0xc420108000, 0xc420065d50)
	/home/travis/.gimme/versions/go/src/testing/testing.go:769 +0x16a
testing.runTests(0xc42000c2a0, 0xb585e0, 0x93, 0x93, 0xc4200ba070)
	/home/travis/.gimme/versions/go/src/testing/testing.go:1034 +0x4c8
testing.(*M).Run(0xc4200ba070, 0x0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:954 +0x272
main.main()
	_testmain.go:504 +0x31f
goroutine 42 [semacquire]:
sync.runtime_Semacquire(0xc42020211c)
	/home/travis/.gimme/versions/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420202110)
	/home/travis/.gimme/versions/go/src/sync/waitgroup.go:129 +0xb3
github.com/miekg/dns.TestConcurrentExchanges(0xc420108780)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:584 +0x32b
testing.tRunner(0xc420108780, 0x942160)
	/home/travis/.gimme/versions/go/src/testing/testing.go:769 +0x16a
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:812 +0x536
goroutine 43 [IO wait]:
internal/poll.runtime_pollWait(0x7f0c15b57f60, 0x72, 0x0)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc42010d298, 0x72, 0xc420051800, 0x1, 0xc420016ae0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0xe5
internal/poll.(*pollDesc).waitRead(0xc42010d298, 0xc420206000, 0x200, 0x200)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).ReadMsg(0xc42010d280, 0xc420206000, 0x200, 0x200, 0xc420016ae0, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:202 +0x283
net.(*netFD).readMsg(0xc42010d280, 0xc420206000, 0x200, 0x200, 0xc420016ae0, 0x28, 0x28, 0x0, 0x2, 0x8, ...)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:214 +0xa1
net.(*UDPConn).readMsg(0xc42000e1a0, 0xc420206000, 0x200, 0x200, 0xc420016ae0, 0x28, 0x28, 0xc420046800, 0x7f0c15b15fa0, 0x7f0c15c67000, ...)
	/home/travis/.gimme/versions/go/src/net/udpsock_posix.go:59 +0xb3
net.(*UDPConn).ReadMsgUDP(0xc42000e1a0, 0xc420206000, 0x200, 0x200, 0xc420016ae0, 0x28, 0x28, 0x0, 0xc420046800, 0x0, ...)
	/home/travis/.gimme/versions/go/src/net/udpsock.go:139 +0xb4
github.com/miekg/dns.ReadFromSessionUDP(0xc42000e1a0, 0xc420206000, 0x200, 0x200, 0x200, 0x200, 0xb5b480, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/udp.go:23 +0xdd
github.com/miekg/dns.(*Server).readUDP(0xc4200afa40, 0xc42000e1a0, 0x34630b8a000, 0x0, 0x0, 0x0, 0x45dd2b, 0xc420051dc0, 0x8)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:628 +0x12d
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc42000e1c8, 0xc42000e1a0, 0x34630b8a000, 0x97ace0, 0xc420085ec0, 0x979800, 0xc42002e600, 0xc4201f9e00, 0x19)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:254 +0x8c
github.com/miekg/dns.(*Server).serveUDP(0xc4200afa40, 0xc42000e1a0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:504 +0x24a
github.com/miekg/dns.(*Server).ActivateAndServe(0xc4200afa40, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:397 +0x517
github.com/miekg/dns.RunLocalUDPServerWithFinChan.func1(0xc4200afa40, 0xc420026f60, 0x97e240, 0xc42000e1a0)
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:72 +0x39
created by github.com/miekg/dns.RunLocalUDPServerWithFinChan
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:71 +0x2bd
goroutine 47 [chan send]:
github.com/miekg/dns.TestConcurrentExchanges.func1(0x97e4e0, 0xc42010d500, 0xc42010b3b0)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:546 +0xa3
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc4201fe500, 0x97e4e0, 0xc42010d500, 0xc42010b3b0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:84 +0x6a
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc42002e600, 0x97e4e0, 0xc42010d500, 0xc42010b3b0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:210 +0xeb
github.com/miekg/dns.(*Server).serve(0xc4200afa40, 0x97ace0, 0xc420085ec0, 0x979800, 0xc42002e600, 0xc4201f9e00, 0x19, 0x200, 0xc42000e1a0, 0xc4201fe6a0, ...)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:558 +0x920
created by github.com/miekg/dns.(*Server).serveUDP
	/home/travis/gopath/src/github.com/miekg/dns/server.go:514 +0x3ec
rax    0xca
rbx    0xc42002e000
rcx    0x488633
rdx    0x0
rdi    0xb5bf40
rsi    0x0
rbp    0x7ffdf5151ec8
rsp    0x7ffdf5151e78
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc420061f28
r13    0xb5be20
r14    0xc42012ca80
r15    0x943498
rip    0x488631
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
exit status 2
FAIL	github.com/miekg/dns	600.005s
~~~

**Comment by miekg** [comment]
Hmmm, doesn't look to be the PR I mentioned. Maybe we hit the `t.Fatalf("response %d is nil", i)` which then doesn't decrements the waitgroup.

**Comment by miekg** [comment]
note: it is the test that uses `tip`
