### ISSUE TITLE
concurrent test failure: data race

### ISSUE THREAD

**Issue by miekg** [miekg/dns#772]
Pasting here to save it:

Hope it is in the test only.

~~~
WARNING: DATA RACE
Write at 0x00c00009e0f8 by goroutine 40:
  github.com/miekg/dns.TestConcurrentExchanges()
      /home/travis/gopath/src/github.com/miekg/dns/client_test.go:538 +0x41c
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x162
Previous read at 0x00c00009e0f8 by goroutine 44:
  github.com/miekg/dns.TestConcurrentExchanges.func1()
      /home/travis/gopath/src/github.com/miekg/dns/client_test.go:543 +0x5c
  github.com/miekg/dns.HandlerFunc.ServeDNS()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:52 +0x69
  github.com/miekg/dns.(*ServeMux).ServeDNS()
      /home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0xf5
  github.com/miekg/dns.(*Server).serveDNS()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:665 +0x2e4
  github.com/miekg/dns.(*Server).serve()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:570 +0x733
  github.com/miekg/dns.(*Server).worker()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:268 +0x3c4
Goroutine 40 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:878 +0x650
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x162
  testing.runTests()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:594 +0x332
Goroutine 44 (running) created at:
  github.com/miekg/dns.(*Server).spawnWorker()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:283 +0xfb
  github.com/miekg/dns.(*Server).serveUDP()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:549 +0x74d
  github.com/miekg/dns.(*Server).ActivateAndServe()
      /home/travis/gopath/src/github.com/miekg/dns/server.go:395 +0x4e8
  github.com/miekg/dns.RunLocalUDPServerWithFinChan.func1()
      /home/travis/gopath/src/github.com/miekg/dns/server_test.go:83 +0x38
==================
SIGQUIT: quit
PC=0x488a61 m=0 sigcode=0
goroutine 0 [idle]:
runtime.futex(0xf01020, 0x80, 0x0, 0x0, 0x0, 0x1725380, 0x0, 0x0, 0x7fff93fabec0, 0x433b52, ...)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0xf01020, 0x0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xf01020)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc00003c000, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000001500)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc00011c100, 0xad988e, 0x17, 0xaf6d28, 0xc0000e7b01)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:879 +0x689
testing.runTests.func1(0xc00011c100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc00011c100, 0xc0000e7d20)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x163
testing.runTests(0xc0000aa360, 0xefd600, 0xb8, 0xb8, 0xc0000e7dc8)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc00017e000, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:594 +0x333
goroutine 33 [select]:
github.com/miekg/dns.(*Server).ShutdownContext(0xc00011ce00, 0xb717e0, 0xc00009a010, 0xc000001980, 0xaf6ac8)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:446 +0x421
github.com/miekg/dns.(*Server).Shutdown(0xc00011ce00, 0xc000029760, 0xa)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:409 +0x7d
github.com/miekg/dns.TestConcurrentExchanges(0xc00011cd00)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:590 +0x967
testing.tRunner(0xc00011cd00, 0xaf6d28)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:878 +0x651
goroutine 50 [semacquire]:
sync.runtime_Semacquire(0xc00009b258)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00009b250)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/sync/waitgroup.go:130 +0xb5
github.com/miekg/dns.(*Server).serveUDP.func1(0xc00009b250, 0xc00011ce00)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:525 +0x51
github.com/miekg/dns.(*Server).serveUDP(0xc00011ce00, 0xc00009e100, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:535 +0x3fa
github.com/miekg/dns.(*Server).ActivateAndServe(0xc00011ce00, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:395 +0x4e9
github.com/miekg/dns.RunLocalUDPServerWithFinChan.func1(0xc0000a0a80, 0xc00011ce00, 0xb73e60, 0xc00009e100)
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:83 +0x39
created by github.com/miekg/dns.RunLocalUDPServerWithFinChan
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:82 +0x30d
goroutine 43 [chan send]:
github.com/miekg/dns.TestConcurrentExchanges.func1(0xb74160, 0xc00018db80, 0xc000180bd0)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:546 +0xa3
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0000ab5e0, 0xb74160, 0xc00018db80, 0xc000180bd0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:52 +0x6a
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc0000aa300, 0xb74160, 0xc00018db80, 0xc000180bd0)
	/home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0xf6
github.com/miekg/dns.(*Server).serveDNS(0xc00011ce00, 0xc00018db80)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:665 +0x2e5
github.com/miekg/dns.(*Server).serve(0xc00011ce00, 0xc00018db80)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:570 +0x734
github.com/miekg/dns.(*Server).worker(0xc00011ce00, 0xc00018da80)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:268 +0x3c5
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/travis/gopath/src/github.com/miekg/dns/server.go:283 +0xfc
~~~

**Comment by tmthrgd** [comment]
I saw this too but didn't have time to investigate. There is a race but it's only in the test.

The handler references `m` from the for loop in a different goroutine:
```go
for _, m := range cases {
```

This is an easy fix.
