### ISSUE TITLE
ZoneParser doesn't validate hex/base64 fields

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#948]
The `ZoneParser` code doesn't validate that hex fields are actually valid hex.

The following test case fails:
```go
func TestParsingInvalidHex(t *testing.T) {
	rr, err := NewRR(`miek.nl. 3600 IN TYPE1234 \# 3 zz-top`)
	if err != nil {
		return
	}
	t.Error("expected error, got <nil>") //line scan_test.go:200

	if rr == nil {
		return
	}
	t.Errorf("expected nil record, got %v", rr) //line scan_test.go:205

	msg := make([]byte, Len(rr))
	if _, err = PackRR(rr, msg, 0, nil, false); err != nil {
		t.Errorf("unexpected error packing record: %v", err) //line scan_test.go:209
	}
}
```

with this output:
```
--- FAIL: TestParsingInvalidHex (0.00s)
    scan_test.go:200: expected error, got <nil>
    scan_test.go:205: expected nil record, got miek.nl. 3600    CLASS1  TYPE1234        \# 3 zz-top
    scan_test.go:209: unexpected error packing record: encoding/hex: invalid byte: U+007A 'z'
```

The correct behaviour would have been for `NewRR` to return a parsing error.

I found this with some brief fuzzing.

/cc @miekg

**Comment by miekg** [comment]
Does bind check this? Under the motto garbage in; garbage out?
(probably does; but would be nice to double check)

**Comment by tmthrgd** [comment]
The problem is that it then produces an invalid `RR` that `PackRR` chokes on. IMHO anything `ZoneParser` produces should be able to be packed.

**Comment by miekg** [comment]
Fair enough.

**Comment by tmthrgd** [comment]
I'm also seeing this from non-validated base64 fields.

```
	" TYPE49 000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"000000000000000000\x1f"
```

```
panic: illegal base64 data at input byte 70

goroutine 1 [running]:
github.com/tmthrgd/dns.FuzzNewRR(0x7fa3a1c24000, 0x4f, 0x200000, 0xc00005b950)
	/tmp/go-fuzz-build332085670/gopath/src/github.com/tmthrgd/dns/fuzz.go:27 +0x1db
go-fuzz-dep.Main(0x5b84b0)
	/tmp/go-fuzz-build332085670/goroot/src/go-fuzz-dep/main.go:54 +0xb6
main.main()
	/tmp/go-fuzz-build332085670/gopath/src/github.com/tmthrgd/dns/go.fuzz.main/main.go:10 +0x2d
exit status 2
```
I'll try and get to this in the coming days.

**Comment by tmthrgd** [comment]
Nor does it validate the length of TXT fields.

```
	" TYPE13 0 0000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"000000"
```

```
panic: dns: string exceeded 255 bytes in txt

goroutine 1 [running]:
github.com/tmthrgd/dns.FuzzNewRR(0x7ff1075ff000, 0x10a, 0x200000, 0xc000080e00)
	/tmp/go-fuzz-build332085670/gopath/src/github.com/tmthrgd/dns/fuzz.go:27 +0x1db
go-fuzz-dep.Main(0x5b84b0)
	/tmp/go-fuzz-build332085670/goroot/src/go-fuzz-dep/main.go:54 +0xb6
main.main()
	/tmp/go-fuzz-build332085670/gopath/src/github.com/tmthrgd/dns/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by miekg** [comment]
I think this is WAI; garbage in; garbage out

**Comment by miekg** [comment]
another reason not to do this is because it massively slows down things, esp when you know the data you're reading is good. This is why bind has named-checkzone and friends.

this could be better documented, because if you find it surprising other people probably find so too

**Comment by tmthrgd** [comment]
@miekg I'm not sure why it should slow things down in any measurable way. We don't actually have to decode the string.

At the very least I think documenting would be appropriate.
