### ISSUE TITLE
nil pointer dereference on i/o timeout

### ISSUE THREAD

**Issue by BonkaBonka** [miekg/dns#952]
The panic:
```
2019/03/28 13:21:15 DNS query error: read udp 10.x.x.x:58863->y.y.y.y:53: i/o timeout
2019/03/28 13:21:15 DNS query error: read udp 10.x.x.x:59368->y.y.y.y:53: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5d8a26]

goroutine 213 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0xc000074178, 0xc0000740c0, 0xc000045e10, 0xc000045e10, 0x40734b)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/msg.go:761 +0x26
github.com/miekg/dns.(*Msg).Pack(...)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/msg.go:754
github.com/miekg/dns.(*response).WriteMsg(0xc0001f2d20, 0x0, 0x0, 0xc0001ddb00)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:665 +0x5d
main.main.func1.2(0x706760, 0xc0001f2d20, 0xc0001ddb00)
	/home/bonka/build/popo/crash.go:40 +0x8a
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0000882e0, 0x706760, 0xc0001f2d20, 0xc0001ddb00)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:37 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc000088200, 0x706760, 0xc0001f2d20, 0xc0001ddb00)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/serve_mux.go:128 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc0000c4000, 0xc0000ea000, 0x20, 0x200, 0xc0001f2d20)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:603 +0x2b8
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0000c4000, 0xc0000922c0, 0xc0000ea000, 0x20, 0x200, 0xc000096028, 0xc000212f20)
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:549 +0xb2
created by github.com/miekg/dns.(*Server).serveUDP
	/home/bonka/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:479 +0x27a
```

The test harness:
```
package main

import (
	"log"

	"github.com/miekg/dns"
)

func main() {
	var addResolver = func(suffixes []string, nameservers []string, tcp bool) {
		upstream := &dns.Client{}
		if tcp {
			upstream.Net = "tcp"
		}

		query := make(chan *dns.Msg)
		response := make(chan *dns.Msg)

		for _, nameserver := range nameservers {
			go func(nameserver string) {
				ns := nameserver + ":53"
				log.Printf("Resolving domains %v through %v using tcp=%t", suffixes, ns, tcp)

				for {
					msg := <-query
					in, _, err := upstream.Exchange(msg, ns)
					if err != nil {
						log.Printf("DNS query error: %v", err.Error())
					}
					response <- in
				}
			}(nameserver)
		}

		for _, suffix := range suffixes {
			dns.HandleFunc(suffix, func(writer dns.ResponseWriter, msg *dns.Msg) {
				query <- msg
				msg = <-response

				err := writer.WriteMsg(msg)
				if err != nil {
					log.Printf("DNS query response write error: %v", err.Error())
					return
				}
			})
		}
	}

	clientConfig, err := dns.ClientConfigFromFile("/etc/resolv.conf")
	if err != nil {
		log.Fatalf("Error loading resolv.conf: %v", err.Error())
		return
	}

	addResolver([]string{"."}, clientConfig.Servers, false)

	server := &dns.Server{Addr: "127.0.0.1:53", Net: "udp"}
	err = server.ListenAndServe()
	if err != nil {
		log.Fatalf("DNS server error: %v", err.Error())
	}
}
```

**Comment by BonkaBonka** [comment]
To run:
```
sudo ./crash &
echo "nameserver 127.0.0.1" | sudo resolvconf -a lo
wait
sudo resolvconf -d lo
```

**Comment by BonkaBonka** [comment]
Ah, geez.  It's my bug: in the event of the timeout I'm still trying to queue the nil response.  I am dumb.
